In [1]:
import pandas as pd
df=pd.read_csv(r'C:/Users/Lenovo/Downloads/netflix_titles.csv')

In [2]:
import sqlalchemy as sal

engine = sal.create_engine(
    "mssql+pyodbc://@.\\SQLEXPRESS/master?"
    "driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

conn = engine.connect()

In [3]:
from sqlalchemy.types import NVARCHAR
df.to_sql('netflix_raw', con=conn , index=False, if_exists = 'replace',dtype={
        'title': NVARCHAR(300),
        'director': NVARCHAR(500),
        'cast': NVARCHAR(None),
        'description': NVARCHAR(None)
    })
conn.close()

In [8]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [10]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [6]:
df[df.show_id=='s5975']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5974,s5975,TV Show,แผนร้ายนายเจ้าเล่ห์,NaN,"Chutavuth Pattarakampol, Sheranut Yusananda, N...",NaN,"March 30, 2019",2016,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...","When two brothers fall for two sisters, they q..."

In [7]:
max(df.description.dropna().str.len())

248